### ISSUE TITLE
public list clean-up on production

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#278] opened 2016-11-07 16:25 UTC
remove the following:
* "_Jungle book"
* "Official list of the birds  ..." 
* "My bird list"
* "Top 40 .."

Add the top 20 list instead.  That one is better.

**Comment by hdliv** [comment] 2016-11-07 16:34
@arlin i cant remove lists that arent mine

**Comment by hdliv** [comment] 2016-11-07 16:35
and the official i also cant remove

**Comment by arlin** [comment] 2016-11-07 17:05
managing the public lists is a requirement and it is our responsibility.  let's get together later today to figure out how to do it. if we can't do it, then we will have to work with @abusalehmdtayeen to change the list server API so that it satisfies our requirement.

**Comment by hdliv** [comment] 2016-11-07 17:13
i have had @ducvan0212 remove lists earlier that I had no access.

**Comment by hdliv** [comment] 2016-11-07 17:14
@arlin if the jubgle book is your list and the 40 species are yours too.  then you can remove them

**Comment by arlin** [comment] 2016-11-07 17:16
let's get together later today to figure out how to do it.  i'll stop by your cubicle at 2:00 pm.

**Comment by ducvan0212** [comment] 2016-11-07 18:13
@arlin For now, Abu hides owner's identity in public list response so the portal can not check to enable user edition. There are 2 workarounds:
- Use API to edit list
- I update list records in portal database so you can edit the public list through portal interface.

**Comment by abusalehmdtayeen** [comment] 2016-11-07 20:33
I hide the user_id which is the gmail address of a owner of a  public list from the results because I think some users may not be comfortable to make the email address publicly visible. If that is not an issue, I can add the user_id to the result and @ducvan0212  can create an option in the portal interface to edit the list.

**Comment by arlin** [comment] 2016-12-01 16:49
@hdliv, let's sit down and do this some time soon.  @abusalehmdtayeen says " please follow the steps in https://github.com/phylotastic/phylo_services_docs/blob/master/SpeciesListServer/Dev_SpeciesListServicesDescription.md#how-to-get-access-token-to-use-in-species-list-web-services to get a token."

**Comment by hdliv** [comment] 2016-12-01 16:52
@arlin I still get an error with this.  How about you?

**Comment by abusalehmdtayeen** [comment] 2016-12-01 19:09
@hdliv , are you getting error retrieving the token or deleting a list?

**Comment by arlin** [comment] 2018-04-11 21:08
This problem just keeps getting worse.  There are about 60 pages of the same thing.  

![Screen Shot 2018-04-11 at 5.07.34 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/555b5266657c0c8300c2bee1/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455f26b7191a37df1122c4f5c5b5ecc3c4a4356bcbbd671f3e57862804e0ee8d43f5a76c16842f8e9d74eea04ec208b4b87e5b5dc49d2f42f67b6d5db1063474f4dcbed5727a19141c95df448e54555ad133067e5742431.png)

**Comment by ducvan0212** [comment] 2018-04-12 02:50
@abusalehmdtayeen I checked and saw the redundancy is also available on List service. I will remove the redundant records in portal production server but the root of the problem is in list service. Can you remove redundant lists from list server as well?

**Comment by abusalehmdtayeen** [comment] 2018-04-12 14:11
@ducvan0212 , I will remove the redundant lists.

**Comment by arlin** [comment] 2018-04-24 17:47
@abusalehmdtayeen, assigning this to you.   I see that you have cleaned up the list.  Thanks.  Did you fix the problem that was adding copies of the bird list?

**Comment by abusalehmdtayeen** [comment] 2018-04-25 02:55
@arlin , I did not find any problem. I just removed the records that were inserted before for testing.  I am closing this issue.

**Comment by abusalehmdtayeen** [comment] 2018-04-26 13:59
I have reopened this issue since I see the problem still exists. Some script is automatically inserting a single list to the production server periodically. I need to find that and remove it.

**Closed** 2018-05-11 17:34 UTC
Labels: in progress
